### ISSUE TITLE
Error while connecting to Solr using Docker

### ISSUE THREAD

**Issue by fgnm** [ewg118/numishare#103]
Hello, I've used the provided Docker instructions to deploy Numishare, however I'm getting some troubles to properly running it. I was successfully be able to run: Orbeon, Solr and Exist; added Tomcat users and roles; Create `numishare` core in Solr. It works, most of settings were already provided in `docker` folder to match the wiki settings (I had only a small issue with Solr folder permission).
Now, whenever I try to add something to a test collection I got this error: `Data Failed to POST to Solr. Index may be offline or URL is incorrect.`

![Schermata del 2021-05-18 14-20-05](https://user-images.githubusercontent.com/5543339/118649783-308e7100-b7e4-11eb-9813-d9a8fea58792.png)

Inside `Modify Settings -> Advanced Settings`, the Solr URL points to: `http://localhost:8983/solr/numishare/` which is correct, because from browser I can access Solr console (this works: http://localhost:8983/solr/#/numishare/core-overview).

Can you pleas help to understand what's going wrong? No error messages appears in terminal except for this one at startup:
```
orbeon    | 18-May-2021 11:35:58.785 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
orbeon    | 18-May-2021 11:35:58.785 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.35]
orbeon    | 18-May-2021 11:35:58.798 INFO [main] org.apache.catalina.startup.HostConfig.deployDescriptor Deploying deployment descriptor [/usr/local/tomcat/conf/Catalina/localhost/ROOT.xml]
exist     | 18 May 2021 11:35:58,804 [main] WARN  (Configuration.java [getConfigAttributeValue]:1528) - Configuration value overridden by system property: org.exist.db-connection.cacheSize, with value: 256M 
exist     | 18 May 2021 11:35:58,814 [main] INFO  (Configuration.java [configureStartup]:1275) - Registered StartupTrigger: org.exist.security.BouncyCastleJceProviderStartupTrigger 
exist     | 18 May 2021 11:35:58,815 [main] INFO  (Configuration.java [configureStartup]:1275) - Registered StartupTrigger: org.exist.protocolhandler.URLStreamHandlerStartupTrigger 
exist     | 18 May 2021 11:35:58,816 [main] INFO  (Configuration.java [configureStartup]:1275) - Registered StartupTrigger: org.exist.extensions.exquery.restxq.impl.RestXqStartupTrigger 
exist     | 18 May 2021 11:35:58,817 [main] INFO  (Configuration.java [configureStartup]:1275) - Registered StartupTrigger: org.exist.repo.AutoDeploymentTrigger 
exist     | 18 May 2021 11:35:58,817 [main] WARN  (Configuration.java [getConfigAttributeValue]:1528) - Configuration value overridden by system property: org.exist.db-connection.pool.max, with value: 20 
solr      | 2021-05-18 11:35:58.847 WARN  (main) [   ] o.e.j.x.XmlConfiguration Ignored arg: <Arg name="threadpool">
solr      |     <New id="threadpool" class="com.codahale.metrics.jetty9.InstrumentedQueuedThreadPool"><Arg name="registry">
solr      |         <Call id="solrJettyMetricRegistry" name="getOrCreate" class="com.codahale.metrics.SharedMetricRegistries"><Arg>solr.jetty</Arg></Call>
solr      |       </Arg></New>
solr      |   </Arg>
orbeon    | 18-May-2021 11:35:58.854 SEVERE [main] org.apache.catalina.startup.HostConfig.deployDescriptor Error deploying deployment descriptor [/usr/local/tomcat/conf/Catalina/localhost/ROOT.xml]
orbeon    | 	java.lang.IllegalStateException: Error starting child
orbeon    | 		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:720)
orbeon    | 		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
orbeon    | 		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
orbeon    | 		at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:631)
orbeon    | 		at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1830)
orbeon    | 		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
orbeon    | 		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
orbeon    | 		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
orbeon    | 		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
orbeon    | 		at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:526)
orbeon    | 		at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:425)
orbeon    | 		at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
orbeon    | 		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
orbeon    | 		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
orbeon    | 		at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
orbeon    | 		at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
orbeon    | 		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
orbeon    | 		at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
orbeon    | 		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
orbeon    | 		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
orbeon    | 		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
orbeon    | 		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
orbeon    | 		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
orbeon    | 		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
orbeon    | 		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
orbeon    | 		at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
orbeon    | 		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
orbeon    | 		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
orbeon    | 		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
orbeon    | 		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
orbeon    | 		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
orbeon    | 		at org.apache.catalina.startup.Catalina.start(Catalina.java:633)
orbeon    | 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
orbeon    | 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
orbeon    | 		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
orbeon    | 		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
orbeon    | 		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:343)
orbeon    | 		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:474)
orbeon    | 	Caused by: org.apache.catalina.LifecycleException: Failed to start component [org.apache.catalina.webresources.StandardRoot@22d7b4f8]
orbeon    | 		at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
orbeon    | 		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
orbeon    | 		at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4800)
orbeon    | 		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4936)
orbeon    | 		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
orbeon    | 		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
orbeon    | 		... 37 more
orbeon    | 	Caused by: java.lang.IllegalArgumentException: The main resource set specified [/usr/local/tomcat/webapps/ROOT] is not valid
orbeon    | 		at org.apache.catalina.webresources.StandardRoot.createMainResourceSet(StandardRoot.java:751)
orbeon    | 		at org.apache.catalina.webresources.StandardRoot.startInternal(StandardRoot.java:708)
orbeon    | 		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
orbeon    | 		... 41 more
orbeon    | 18-May-2021 11:35:58.856 INFO [main] org.apache.catalina.startup.HostConfig.deployDescriptor Deployment of deployment descriptor [/usr/local/tomcat/conf/Catalina/localhost/ROOT.xml] has finished in [58] ms
```
Looks like `orbeon.xml` has some problems (I haven't touched it).

The second issue is that many of pages seems broken (like this one):
![Schermata del 2021-05-18 14-17-11](https://user-images.githubusercontent.com/5543339/118649505-dc838c80-b7e3-11eb-8534-61b86a37bca9.png)
But I thought this because the Solr error. Please let me know.
Thanks

**Comment by Msch0150** [comment]
As far as I remember, I had the same problem.
I think I fixed it  in numishare/docker/orbeon.xml 



&lt;Context path="/orbeon" docBase="orbeon"&gt;    &lt;Resources allowLinking="true" /&gt;    &lt;Valve className="org.apache.catalina.authenticator.BasicAuthenticator" changeSessionIdOnAuthentication="false"/&gt;&lt;/Context&gt;



So, adding path="/orbeon".

**Comment by Msch0150** [comment]
Info: I adjusted some files to get it to work in my fork:

https://github.com/Msch0150/numishare/tree/master/docker

So, the files core.properties, docker-compose.yml, orbeon.xml and setup.sh were adjusted by me.
Info: I am running it on Docker for Windows and Ubuntu.

**Comment by fgnm** [comment]
@Msch0150 that's really helpful! I've understand my mistakes, many thanks
